name: qa-deploy
on: pull_request
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Init submodule
        run: |
          git submodule update --remote
          ls -la
      - name: Build
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run generate
          npm run build
          npm run predeploy
      - name: Get preview url for hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QA_CCV_BROWN_EDU }}'
          projectId: qa-ccv-brown-edu
          expires: 7d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: clear cj envs to access status org
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:unset gh.token gh.user
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
          PROJECT_ID: qa-ccv-brown-edu
      - name: set cj envs to access status org
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set gh.token='${{ secrets.CJ_GH_REPO_TOKEN }}' gh.user='${{ secrets.CJ_GH_USER }}'
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
          PROJECT_ID: qa-ccv-brown-edu
      - name: Deploy to Firebase
        run: npm run qa-deploy
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
      - name: Remove content folder (extra git module instance confuses gh)
        run: rm -rf functions/content
